version: 2.1
orbs:
  node: circleci/node@1.1.6
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run seed
            - run: npm test
workflows:
  check-build:
    jobs:
      - shellcheck/check
      - build-and-test:
          requires:
            - shellcheck/check
